baseURL = "http://localhost:1313"
languageCode = "en-us"

title = "MSOS project webpage"
theme = "kraiklyn"

pygmentsCodeFences = true 
pygmentsStyle = "monokailight"

[params]
externalTitle = "MSOS project webpage"
sidebarColor = "default"
customCss = [] 


